accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

mysite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('<int:content_id>/', views.detail, name='detail'),
    path('collection/', views.collection, name='collection'),
    path('additem/', views.additem, name='additem'),
    path('comment/create/<int:content_id>/', views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('collection/', views.collection),
]

testApp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('result/', views.result, name='result'),
    path('add/', views.add, name='add'),
]

accounts/models.py
from django.db import models

# Create your models here.

mysite/models.py
# Create your models here.

from django.db import models
from django.contrib.auth.models import User


class MainContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content_list = models.ForeignKey(MainContent, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

testApp/models.py
from django.db import models

# Create your models here.


class AiClass(models.Model):
    class_num = models.IntegerField()
    teacher = models.CharField(max_length=30)
    class_room = models.CharField(max_length=30)
    students_num = models.IntegerField()


class AiStudent(models.Model):
    name = models.CharField(max_length=30)

mysite/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render

# Create your views here.

mysite/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render, redirect
from .models import MainContent, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required


def index(request):
    content_list = MainContent.objects.all()
    context = {'content_list': content_list}
    return render(request, 'mysite/content_list.html', context)


def detail(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)
    context = {'content_list': content_list}
    return render(request, 'mysite/content_detail.html', context)


def collection(request):
    content_list = MainContent.objects.all()
    context = {'content_list': content_list}
    return render(request, 'mysite/collection.html', context)


def additem(request):
    MainContent.objects.create(
        title=request.POST['title'],
        content=request.POST['content'],
    )
    return redirect('collection')


@login_required(login_url='accounts:login')
def comment_create(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.content_list = content_list
            comment.author = request.user
            comment.save()
            return redirect('detail', content_id=content_list.id)
    else:
        form = CommentForm()
    context = {'content_list': content_list, 'form': form}
    return render(request, 'mysite/content_detail.html', context)


@login_required(login_url='accounts:login')
def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        raise PermissionDenied

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('detail', content_id=comment.content_list.id)
    else:
        form = CommentForm(instance=comment)

    context = {'comment': comment, 'form': form}
    return render(request, 'mysite/comment_form.html', context)


@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        raise PermissionDenied
    else:
        comment.delete()
    return redirect('detail', content_id=comment.content_list.id)

pages/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render


def collection(request):
    return render(request, 'pages/collection.html')

testApp/views.py
from django.shortcuts import render, redirect
from .models import AiClass, AiStudent


# Create your views here.


def home(request):
    class_object = AiClass.objects.all()
    student_object = AiStudent.objects.all()
    return render(request, 'test/home.html', {'class_object': class_object, 'student_object': student_object})


def result(request):
    name = request.POST['username']
    students = ['inu', 'james', 'bob']

    if name in students:
        is_exist = True
    else:
        is_exist = False

    return render(request, 'test/result.html', {'user_name': name, 'is_exist': is_exist})


def add(request):
    if request.method == 'POST':
        AiStudent.objects.create(
            name=request.POST['name']
        )
        return redirect('home')
    return render(request, 'test/add.html')

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
<p>아이디 또는 비밀번호가 틀립니다. 다시 시도해주세요.</p>
{% endif %}

<form method="POST" action="{% url 'accounts:login' %}">
    {%  csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="login" >
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Heroic Features - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"/>
    </head>
    <body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
    </body>
</html>

templates/footer.html
 <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; ICE KREAM 2022</p></div>
        </footer>

templates/mysite/collection.html
{% extends 'base.html' %}
{% block content %}
    <h1>collection list</h1>
    {% if content_list %}
        {% for content in content_list %}
             <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-collection"></i></div>
                        <h2 class="fs-4 fw-bold">{{ content.title }}</h2>
                        <p class="mb-0">{{ content.content | truncatewords:20}}</p>
                        <a href="{% url 'detail' content.id %}" >detail</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p> 아직 추가된 신발이 없습니다.</p>
    {% endif %}

    <form action="{% url 'additem' %}" method="POST">
        {% csrf_token %}
        <input name="title" placeholder="title"/>
        <input name="content" placeholder="content"/>
        <br/>
        <button type="submit">Add</button>
    </form>
{% endblock %}

templates/mysite/comment_form.html
{% extends 'base.html' %}
{% block content %}
<h2>update comment</h2>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" action="{% url 'comment_update' comment.id %}" class="mb-4">
                {% csrf_token %}
                <textarea name="content" id="content" rows="3" class="form-control">
                    {{ form.content.value }}
                </textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/mysite/content_detail.html
{% extends 'base.html' %}
{% block content %}
<h3>{{ content_list.title }}</h3>
<p>{{ content_list.content }}</p>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="POST" class="mb-4" action="{% url 'comment_create' content_list.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" rows="3" class="form-control" placeholder="내용을 입력해주세요"></textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
            {% for comment in content_list.comment_set.all %}
            <div class="d-flex">
                <div class="ms-3">
                    <div class="fw-body">
                        {{ comment.author.username }}&nbsp {{ comment.create_date }}
                        {% if comment.create_date != comment.modify_date %}
                        / 수정일자: {{ comment.modify_date }}
                        {% endif %}
                        {% if request.user == comment.author %}
                        <a href="{% url 'comment_update' comment.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="{% url 'comment_delete' comment.id %}" class="btn btn-sm btn-outline-secondary">삭제</a>
                        {% endif %}
                    </div>
                    {{ comment.content }}
                </div>
            </div>
            <br/>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/mysite/content_list.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">
                <h1 class="display-5 fw-bold">진행중인 Lucky Draw</h1>
                <p class="fs-4" >
                    7월 더블 럭키 드로우 한 번에 두 상품 응모!<br/>
                    응모기간도 수 - 금요일까지!<br/>
                    <br/>
                    ◎ 드로우 일정<br/>
                    매주 수 오후 12시 - 금 오후 12시까지<br/>
                    <br/>
                    ◎ 당첨자 발표<br/>
                    드로우 다음 주 월 오후 6시<br/>
                    (공지 사항 게시 및 당첨자에게 메시지 전송)
                </p>
                <a class="btn btn-primary btn-lg" href="https://kream.co.kr/">응모하기</a>
            </div>
        </div>
    </div>
</header>
<!-- Page Content-->
<section class="pt-4">
    <div class="container px-lg-5">
        <!-- Page Features-->
        <div class="row gx-lg-5">
            {% if content_list %}
                {% for content in content_list %}
                     <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-collection"></i></div>
                                <h2 class="fs-4 fw-bold">{{ content.title }}</h2>
                                <p class="mb-0">{{ content.content | truncatewords:20}}</p>
                                <a href="{% url 'detail' content.id %}" >자세히보기</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p> content가 없습니다.</p>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

templates/navbar.html
 <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <a class="navbar-brand" href="/">ICE KREAM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="/collection">Collection</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }}(logout)</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>